import {FormEvent,useMemo,useState} from "react"
import {useRouter} from "next/router"

function paymentToken(value:string){const v=value.trim();if(!v)return "";try{const u=new URL(v),p=u.pathname.split("/").filter(Boolean);if(p[0]==="pay"&&p[1])return decodeURIComponent(p[1])}catch{}return decodeURIComponent(v.replace(/^\/+/,"").replace(/^pay\//,""))}

export default function Home(){const router=useRouter(),[invoice,setInvoice]=useState(""),token=useMemo(()=>paymentToken(invoice),[invoice]);function openInvoice(e:FormEvent){e.preventDefault();if(token)router.push(`/pay/${encodeURIComponent(token)}`)}return <main className="min-h-screen bg-[#f5f7fb] text-[#172033]">
 <header className="border-b bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-4 py-4"><div><b className="text-xl text-[#17634f]">Rentomatic</b><p className="text-xs text-slate-500">Renting, simplified for everyone</p></div><div className="flex gap-2"><a href="https://app.rentomatic.in/login" className="rounded-full border px-4 py-2 text-sm font-semibold">Landlord sign in</a><button onClick={()=>router.push("/login")} className="rounded-full bg-[#17634f] px-4 py-2 text-sm font-semibold text-white">Tenant sign in</button></div></div></header>
 <section className="mx-auto grid max-w-6xl items-center gap-8 px-4 py-14 lg:grid-cols-[1.1fr_.9fr]"><div><span className="rounded-full bg-emerald-50 px-3 py-1 text-sm font-semibold text-[#17634f]">One platform for landlords and tenants</span><h1 className="mt-5 max-w-2xl text-5xl font-bold leading-tight">Bills, maintenance and documents without the confusion.</h1><p className="mt-5 max-w-xl text-lg leading-8 text-slate-600">Choose your portal. Landlords manage properties and collections; tenants use their assigned Gmail and Tenant ID to access the right home.</p><div className="mt-7 grid max-w-xl gap-3 sm:grid-cols-2"><a href="https://app.rentomatic.in/login" className="rounded-2xl border bg-white p-5 shadow-sm hover:border-[#17634f]"><b className="text-lg">I’m a landlord</b><span className="mt-2 block text-sm text-slate-500">Manage tenants, billing and properties</span><span className="mt-3 block font-semibold text-[#17634f]">Landlord sign in →</span></a><button onClick={()=>router.push("/login")} className="rounded-2xl bg-[#17634f] p-5 text-left text-white shadow-sm"><b className="text-lg">I’m a tenant</b><span className="mt-2 block text-sm text-emerald-50">Pay bills, report issues and open documents</span><span className="mt-3 block font-semibold">Tenant sign in →</span></button></div><a href="#invoice" className="mt-5 inline-block text-sm font-semibold text-slate-600 underline">Open an invoice without signing in</a></div>
 <div className="grid gap-3 sm:grid-cols-2"><Feature title="Bills & receipts" text="One clear bill per month with payment history."/><Feature title="Maintenance" text="Report an issue with a photo and track its status."/><Feature title="Document vault" text="Securely share PDFs and images with your manager."/><Feature title="Tenant IDs" text="One Gmail can access multiple tenancies safely."/></div></section>
 <section id="invoice" className="border-y bg-white"><div className="mx-auto grid max-w-6xl gap-8 px-4 py-12 md:grid-cols-2"><div><p className="font-semibold text-[#17634f]">Have an invoice link?</p><h2 className="mt-2 text-3xl font-bold">Open it without signing in</h2><p className="mt-3 text-slate-600">Paste the secure payment link from your invoice email. Existing payment links continue to work exactly as before.</p></div><form onSubmit={openInvoice} className="rounded-2xl border bg-[#f8fafc] p-5"><label className="text-sm font-semibold">Payment link or token<textarea value={invoice} onChange={e=>setInvoice(e.target.value)} rows={3} placeholder="https://rentomatic.in/pay/your-token" className="mt-2 w-full resize-none rounded-xl border bg-white p-3"/></label><button disabled={!token} className="mt-3 w-full rounded-xl bg-[#17634f] p-3 font-bold text-white disabled:opacity-40">Open invoice</button></form></div></section>
 <footer className="mx-auto flex max-w-6xl flex-wrap justify-between gap-3 px-4 py-8 text-sm text-slate-500"><span>© Rentomatic</span><span>Private access · Secure documents · Clear records</span></footer>
 </main>}
function Feature({title,text}:{title:string;text:string}){return <div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-3 h-9 w-9 rounded-xl bg-emerald-100"/><h2 className="font-bold">{title}</h2><p className="mt-1 text-sm leading-6 text-slate-500">{text}</p></div>}
