import axios from "axios"
import {FormEvent,useEffect,useMemo,useState} from "react"
import {useRouter} from "next/router"
import {tenantAuth} from "../lib/tenantAuth"
import {OWNER_BACKEND_BASE_URL} from "../lib/sharedRules"

type Invoice={id:string;invoice_number?:string;due_date?:string;amount:number;paid_amount?:number;credited_amount?:number;refunded_amount?:number;late_fee_paise?:number;grace_period_days?:number;status:string;payment_token?:string}
type Dashboard={rentId:string;tenantId?:string;tenantName?:string;tenantEmail:string;invoices:Invoice[];maintenance:any[];leases:any[];documents:any[];notifications:any[];deposit?:{originalAmountPaise:number};depositEntries:any[]}
type Tab="home"|"bills"|"maintenance"|"documents"|"lease"
const api=process.env.NEXT_PUBLIC_BACKEND_BASE_URL||OWNER_BACKEND_BASE_URL
const money=(p:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(p/100)
const outstanding=(invoice:Invoice)=>Math.max(0,invoice.amount+(invoice.late_fee_paise||0)-(invoice.paid_amount||0)-(invoice.credited_amount||0))
const title=(s:string)=>s.replace(/_/g," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase())

export default function TenantHome(){
 const router=useRouter(),[items,setItems]=useState<Dashboard[]>([]),[selected,setSelected]=useState(0),[tab,setTab]=useState<Tab>("home"),[error,setError]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false)
 const [issue,setIssue]=useState({title:"",description:"",priority:"MEDIUM"}),[photo,setPhoto]=useState<File|null>(null)
 const [vault,setVault]=useState({title:"",category:"OTHER"}),[vaultFile,setVaultFile]=useState<File|null>(null),[message,setMessage]=useState(""),[progress,setProgress]=useState(0)
 async function token(){return (await tenantAuth?.auth.getSession()).data.session?.access_token}
 async function load(){const access=await token();if(!access){router.replace("/login");return}try{const r=await axios.get(`${api}/tenant/me`,{headers:{Authorization:`Bearer ${access}`}});setItems(r.data.accounts);setError("")}catch(e){setError(axios.isAxiosError(e)?String(e.response?.data?.message||e.message):"Could not load your tenant portal")}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const d=items[selected]
 const openBills=useMemo(()=>d?.invoices.filter(x=>["ISSUED","PARTIALLY_PAID","OVERDUE","PENDING","UNPAID"].includes(x.status))||[],[d]),paid=useMemo(()=>d?.invoices.filter(x=>x.status==="PAID")||[],[d])
 async function logout(){await tenantAuth?.auth.signOut();router.replace("/login")}
 async function report(e:FormEvent){e.preventDefault();if(!d)return;setBusy(true);setError("");setMessage("");try{const access=await token();let photoBase64:string|undefined;if(photo)photoBase64=await fileData(photo);await axios.post(`${api}/tenant/maintenance`,{rentId:d.rentId,...issue,photoBase64,photoFileName:photo?.name,photoMimeType:photo?.type},{headers:{Authorization:`Bearer ${access}`}});setIssue({title:"",description:"",priority:"MEDIUM"});setPhoto(null);setMessage("Maintenance request submitted. Your property manager can now review it.");await load()}catch(e){setError(axios.isAxiosError(e)?String(e.response?.data?.message||e.message):"Could not submit request")}finally{setBusy(false)}}
 async function openDoc(id:string){try{const access=await token();const r=await axios.get(`${api}/tenant/documents/${id}`,{headers:{Authorization:`Bearer ${access}`}});window.open(r.data.url,"_blank","noopener,noreferrer")}catch{setError("Could not open this document")}}
 async function uploadDoc(e:FormEvent){e.preventDefault();if(!d||!vaultFile)return;setBusy(true);setError("");setMessage("");try{if(!["application/pdf","image/jpeg","image/png","image/webp"].includes(vaultFile.type))throw new Error("Choose a PDF, JPG, PNG or WebP file.");if(vaultFile.size>10*1024*1024)throw new Error("File must be 10 MB or smaller.");const access=await token();setProgress(20);await axios.post(`${api}/tenant/documents`,{rentId:d.rentId,title:vault.title,category:vault.category,fileName:vaultFile.name,mimeType:vaultFile.type,documentBase64:await fileData(vaultFile),tenantVisible:true},{headers:{Authorization:`Bearer ${access}`},onUploadProgress:e=>e.total&&setProgress(20+Math.round(e.loaded/e.total*80))});setVault({title:"",category:"OTHER"});setVaultFile(null);setProgress(100);setMessage("Document uploaded securely and shared with your property manager.");await load()}catch(e){setError(axios.isAxiosError(e)?String(e.response?.data?.message||e.message):e instanceof Error?e.message:"Could not upload document")}finally{setBusy(false);setTimeout(()=>setProgress(0),800)}}
 async function reopen(id:string){const reason=prompt("Tell your property manager why this needs more work")?.trim();if(!reason)return;const access=await token();await axios.post(`${api}/tenant/maintenance/${id}/reopen`,{reason},{headers:{Authorization:`Bearer ${access}`}});setMessage("Request reopened and your property manager was notified.");await load()}
 async function acknowledgeLease(id:string){const note=prompt("Optional acknowledgement note")||undefined;const access=await token();await axios.post(`${api}/tenant/leases/${id}/acknowledge`,{note},{headers:{Authorization:`Bearer ${access}`}});setMessage("Lease acknowledged.");await load()}
 async function openLease(id:string){const access=await token();const r=await axios.get(`${api}/tenant/leases/${id}/download`,{headers:{Authorization:`Bearer ${access}`}});window.open(r.data.url,"_blank","noopener,noreferrer")}
 if(loading)return <Message text="Opening your tenant portal…"/>
 if(!d)return <Message text={error||"Your Gmail is not assigned to a Tenant ID yet. Ask your property manager to add it."}/>
 const balance=(d.deposit?.originalAmountPaise||0)+d.depositEntries.filter(x=>x.entryType==="ADJUSTMENT_CREDIT").reduce((s,x)=>s+x.amountPaise,0)-d.depositEntries.filter(x=>["DEDUCTION","REFUND","ADJUSTMENT_DEBIT"].includes(x.entryType)).reduce((s,x)=>s+x.amountPaise,0)
 return <main className="min-h-screen bg-[#f5f7fb] text-[#172033]"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4"><div><b className="text-xl text-[#17634f]">Rentomatic</b><p className="text-xs text-slate-500">Tenant portal</p></div><button onClick={logout} className="rounded-full border px-4 py-2 text-sm font-semibold">Sign out</button></div></header>
 <div className="mx-auto grid max-w-7xl gap-6 px-4 py-6 md:grid-cols-[230px_1fr]"><aside className="h-fit rounded-2xl border bg-white p-3 shadow-sm"><label className="block p-2 text-xs font-bold uppercase tracking-wide text-slate-500">Your tenancy</label>{items.length>1?<select className="mb-3 w-full rounded-xl border p-3 font-semibold" value={selected} onChange={e=>{setSelected(Number(e.target.value));setTab("home")}}>{items.map((x,i)=><option value={i} key={`${x.tenantId}-${x.rentId}`}>{x.tenantId||"Tenant"} · {x.tenantName}</option>)}</select>:<div className="mb-3 rounded-xl bg-emerald-50 p-3"><b>{d.tenantId||"Tenant ID pending"}</b><p className="text-xs text-slate-600">{d.tenantName}</p></div>}{(["home","bills","maintenance","documents","lease"] as Tab[]).map(x=><button key={x} onClick={()=>setTab(x)} className={`mb-1 w-full rounded-xl px-4 py-3 text-left font-semibold ${tab===x?"bg-[#17634f] text-white":"hover:bg-slate-50"}`}>{title(x)}</button>)}</aside>
 <section><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm text-slate-500">Tenant ID <b className="text-[#17634f]">{d.tenantId||"Being assigned"}</b></p><h1 className="text-3xl font-bold">{tab==="home"?`Hello, ${d.tenantName||d.tenantEmail}`:title(tab)}</h1></div>{items.length>1&&<span className="rounded-full bg-blue-50 px-3 py-1 text-sm text-blue-700">{items.length} tenancies linked to this Gmail</span>}</div>{error&&<p className="mb-4 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}{message&&<p className="mb-4 rounded-xl bg-emerald-50 p-4 text-emerald-800">{message}</p>}
 {tab==="home"&&<><div className="grid gap-4 sm:grid-cols-3"><Stat label="Amount due" value={money(openBills.reduce((sum,invoice)=>sum+outstanding(invoice),0))}/><Stat label="Open requests" value={String(d.maintenance.filter(x=>!["RESOLVED","CLOSED"].includes(x.status)).length)}/><Stat label="Deposit balance" value={d.deposit?money(balance):"Not recorded"}/></div>{d.notifications?.length>0&&<Card title="Recent updates">{d.notifications.slice(0,5).map((n:any)=><div key={n.id} className="border-b py-3"><b>{n.title}</b><p className="text-sm text-slate-600">{n.message}</p></div>)}</Card>}<Card title="Next actions"><div className="grid gap-3 sm:grid-cols-3"><Action text={openBills.length?`${openBills.length} bill${openBills.length>1?"s":""} need attention`:"Rent is up to date"} go={()=>setTab("bills")}/><Action text="Report or track maintenance" go={()=>setTab("maintenance")}/><Action text={`${d.documents.length} shared document${d.documents.length===1?"":"s"}`} go={()=>setTab("documents")}/></div></Card></>}
 {tab==="bills"&&<Card title="Bills & receipts"><h3 className="font-bold">To pay</h3>{openBills.length?openBills.map(x=><Bill key={x.id} x={x} open={()=>x.payment_token&&router.push(`/pay/${x.payment_token}`)}/>):<Empty text="Nothing is due."/>}<h3 className="mt-6 font-bold">Payment history</h3>{paid.length?paid.map(x=><Bill key={x.id} x={x} open={()=>x.payment_token&&router.push(`/pay/${x.payment_token}`)}/>):<Empty text="No receipts yet."/>}</Card>}
 {tab==="maintenance"&&<div className="grid gap-5 lg:grid-cols-2"><Card title="Report an issue"><form onSubmit={report} className="space-y-3"><input required className="input" placeholder="What needs attention?" value={issue.title} onChange={e=>setIssue({...issue,title:e.target.value})}/><textarea required rows={4} className="input" placeholder="Describe the issue and location" value={issue.description} onChange={e=>setIssue({...issue,description:e.target.value})}/><select className="input" value={issue.priority} onChange={e=>setIssue({...issue,priority:e.target.value})}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>URGENT</option></select><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setPhoto(e.target.files?.[0]||null)}/><button disabled={busy} className="w-full rounded-xl bg-[#17634f] p-3 font-bold text-white">{busy?"Submitting…":"Submit request"}</button></form></Card><Card title="Request history">{d.maintenance.length?d.maintenance.map(x=><div key={x.id} className="border-b py-4"><div className="flex justify-between"><b>{x.title}</b><span className="text-sm font-semibold text-[#17634f]">{title(x.status)}</span></div><p className="text-sm text-slate-500">{x.description}</p>{x.ownerNote&&<p className="mt-2 rounded-lg bg-slate-50 p-2 text-sm">Manager: {x.ownerNote}</p>}<div className="mt-2 grid gap-1 text-xs text-slate-500">{x.assigneeName&&<span>Assigned to {x.assigneeName} ({title(x.assigneeType||"staff")})</span>}{x.appointmentAt&&<span>Appointment: {new Date(x.appointmentAt).toLocaleString()}</span>}{x.expectedCompletionAt&&<span>Expected completion: {new Date(x.expectedCompletionAt).toLocaleString()}</span>}{x.estimatedCostPaise!=null&&<span>Estimated cost: {money(x.estimatedCostPaise)}</span>}</div>{["RESOLVED","CLOSED"].includes(x.status)&&<button onClick={()=>reopen(x.id)} className="mt-3 rounded-lg border border-amber-300 px-3 py-2 text-sm font-semibold text-amber-800">Still not fixed? Reopen</button>}</div>):<Empty text="No requests yet."/>}</Card></div>}
 {tab==="documents"&&<div className="grid gap-5 lg:grid-cols-2"><Card title="Document vault">{d.documents.length?d.documents.map(x=><button key={x.id} onClick={()=>openDoc(x.id)} className="flex w-full justify-between border-b py-4 text-left"><span><b>{x.title}</b><small className="block text-slate-500">{title(x.category)} · {x.fileName} · revision {x.revision||1}</small><small className="block text-slate-500">Uploaded by {x.uploadedBy==="TENANT"?"you":"landlord"}{x.expiresOn?` · expires ${x.expiresOn}`:""}</small></span><b className="text-[#17634f]">Preview</b></button>):<Empty text="No documents have been shared yet."/>}</Card><Card title="Upload a document"><form onSubmit={uploadDoc} className="space-y-3"><input required className="input" placeholder="Document title" value={vault.title} onChange={e=>setVault({...vault,title:e.target.value})}/><select className="input" value={vault.category} onChange={e=>setVault({...vault,category:e.target.value})}><option value="KYC">KYC / identity</option><option value="RECEIPT">Receipt</option><option value="OTHER">Other</option></select><input required type="file" accept="application/pdf,image/jpeg,image/png,image/webp" className="input" onChange={e=>setVaultFile(e.target.files?.[0]||null)}/><p className="text-xs text-slate-500">PDF, JPG, PNG or WebP · maximum 10 MB.</p>{progress>0&&<div className="h-2 overflow-hidden rounded bg-slate-200"><div className="h-full bg-[#17634f]" style={{width:`${progress}%`}}/></div>}<button disabled={busy} className="w-full rounded-xl bg-[#17634f] p-3 font-bold text-white">{busy?`Uploading ${progress}%`:"Upload securely"}</button></form></Card></div>}
 {tab==="lease"&&<div className="grid gap-5 lg:grid-cols-2"><Card title="Lease details">{d.leases.length?d.leases.map(x=><div key={x.id} className="border-b py-3"><b>{x.title}</b><p className="text-sm text-slate-500">Ends {x.leaseEndOn} · {title(x.status)}</p><button onClick={()=>openLease(x.id)} className="mt-3 rounded-lg border px-4 py-2 text-sm font-semibold">Review agreement</button>{x.acknowledgedAt?<p className="mt-2 text-sm font-semibold text-emerald-700">Acknowledged {new Date(x.acknowledgedAt).toLocaleDateString()}</p>:x.acknowledgementRequired!==false&&<button onClick={()=>acknowledgeLease(x.id)} className="ml-2 mt-3 rounded-lg bg-[#17634f] px-4 py-2 text-sm font-semibold text-white">Acknowledge agreement</button>}</div>):<Empty text="No lease details shared."/>}</Card><Card title="Security deposit"><div className="flex justify-between"><span>Current balance</span><b>{d.deposit?money(balance):"Not recorded"}</b></div>{d.depositEntries.map(x=><div key={x.id} className="mt-3 flex justify-between border-t pt-3 text-sm"><span>{title(x.entryType)}<small className="block text-slate-500">{x.description}</small></span><b>{money(x.amountPaise)}</b></div>)}</Card></div>}
 </section></div></main>}

function Card({title,children}:{title:string;children:React.ReactNode}){return <div className="mt-5 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="mb-4 text-xl font-bold">{title}</h2>{children}</div>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><b className="mt-1 block text-2xl">{value}</b></div>}
function Action({text,go}:{text:string;go:()=>void}){return <button onClick={go} className="rounded-xl border p-4 text-left font-semibold hover:border-[#17634f] hover:bg-emerald-50">{text}<span className="mt-2 block text-sm text-[#17634f]">View →</span></button>}
function Bill({x,open}:{x:Invoice;open:()=>void}){const due=outstanding(x);return <div className="flex flex-wrap items-center justify-between gap-3 border-b py-4"><span><b>{x.invoice_number||"Rent invoice"}</b><small className="block text-slate-500">Due {x.due_date||"—"} · {title(x.status)}{x.grace_period_days?` · ${x.grace_period_days}-day grace`:""}</small>{x.late_fee_paise?<small className="block text-amber-700">Includes {money(x.late_fee_paise)} late fee</small>:null}</span><span className="text-right"><b>{money(x.status==="PAID"?x.amount+(x.late_fee_paise||0):due)}</b>{(x.paid_amount||x.credited_amount||x.refunded_amount)?<small className="block text-slate-500">Original {money(x.amount)}{x.refunded_amount?` · refunded ${money(x.refunded_amount)}`:""}</small>:null}</span>{x.payment_token&&<button onClick={open} className="rounded-lg bg-[#17634f] px-4 py-2 font-semibold text-white">{x.status==="PAID"?"Receipt":"Pay balance"}</button>}</div>}
function Empty({text}:{text:string}){return <p className="my-3 rounded-xl bg-slate-50 p-4 text-sm text-slate-500">{text}</p>}
function Message({text}:{text:string}){return <main className="grid min-h-screen place-items-center bg-[#f5f7fb] p-6"><div className="max-w-md rounded-2xl border bg-white p-8 text-center shadow-sm"><b className="text-2xl text-[#17634f]">Rentomatic</b><p className="mt-3 text-slate-600">{text}</p></div></main>}
function fileData(file:File){return new Promise<string>((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result));r.onerror=no;r.readAsDataURL(file)})}
